### ISSUE TITLE
Better default error logging 

### ISSUE THREAD

**Issue by satazor** [appgeist/restful-next-api#3]
The default logging of unknown errors could be improved here: https://github.com/appgeist/restful-next-api/blob/master/defaultErrorHandler.js#L16

- It should use `console.error` so that errors are printed to `process.stderr`.
- It doesn't print other error properties, just the stack. In some cases, errors contain other useful properties such as `details` or `code` (e.g.: most of Node.js errors have a `code` property).

My proposal is to change that line to:

```js
console.error(util.inspect(err, false, 5));
```
...so that errors are printed to `stderr` as well as error properties.

**Comment by icflorescu** [comment]
Agreed and merged, thanks. Will republish in a few minutes.
