### ISSUE TITLE
Is http-status-codes really necessary as a peer-dependency?

### ISSUE THREAD

**Issue by satazor** [appgeist/restful-next-api#5]
While `http-status-codes` is used internally to get the error messages, as I user I can use or not use `http-status-codes` in my code, e.g.:

```js
throw new ApiError(403);  // instead of throw new ApiError(FORBIDDEN);
```

Because of that, I would say to make it a dependency instead of a peer-dependency. However, the examples can still use `http-status-codes` for best practices.

**Comment by icflorescu** [comment]
Agreed and merged, thanks. Will republish in a few minutes.
